# Generated by Django 3.1 on 2020-08-18 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Univers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=6)),
                ('dateDeNaissance', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('enLigne', models.BooleanField()),
                ('presentation', models.TextField()),
                ('nombreDEnfant', models.SmallIntegerField()),
                ('presentationVocale', models.FileField(upload_to=None)),
                ('photo', models.ImageField(upload_to=None)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
