# Generated by Django 3.1 on 2020-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univers',
            name='dateDeNaissance',
            field=models.DateField(null=True),
        ),
    ]
