# Generated by Django 3.1 on 2020-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0002_auto_20200819_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univers',
            name='nombreDEnfant',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='univers',
            name='photo',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='univers',
            name='presentation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='univers',
            name='presentationVocale',
            field=models.FileField(null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='univers',
            name='sexe',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='univers',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
