# Generated by Django 3.1 on 2020-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0003_auto_20200819_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univers',
            name='enLigne',
            field=models.BooleanField(null=True),
        ),
    ]
