# Generated by Django 3.1 on 2020-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univers', '0004_auto_20200819_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univers',
            name='photo',
            field=models.ImageField(null=True, upload_to='mediats.images'),
        ),
        migrations.AlterField(
            model_name='univers',
            name='presentationVocale',
            field=models.FileField(null=True, upload_to='mediats.sounds'),
        ),
    ]
